import { createSlice } from "@reduxjs/toolkit";

export const settingsSlice = createSlice({
  name: "settings",
  initialState: {
    transactionSettingsRow: [
      {
        id: "0",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "1",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "2",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "3",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "4",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "5",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "6",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
      {
        id: "7",
        min_send: "300",
        fee: "400",
        decimals: "12 000",
        suspend: "400",
      },
    ],
    swapSettingsRow: [
      {
        id: 0,
        pair: "BTCNGN",
      },
      {
        id: 1,
        pair: "BTCNGN",
      },
      {
        id: 2,
        pair: "BTCNGN",
      },
      {
        id: 3,
        pair: "BTCNGN",
      },
      {
        id: 4,
        pair: "BTCNGN",
      },
      {
        id: 5,
        pair: "BTCNGN",
      },
    ],
    lockedSettingsRow: [
      {
        id: 0,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 1,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 2,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 3,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 4,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 5,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
      {
        id: 6,
        coin_name: "BIT",
        period_one: "1 mouth",
        period_two: "2 mouth",
        air: "35",
        min_amount: "4 mounth",
        status: "active",
        bonus: "120 $",
      },
    ],
    flexibleSettingsRow: [
      {
        id: 0,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 1,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 2,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 3,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 4,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 5,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
      {
        id: 6,
        coin_name: "BIT",
        week_price_one: "30",
        week_price_two: "60",
        week_price_three: "90",
        min_amount: "4 mounth",
        status: "active",
      },
    ],
  },
  reducers: {},
  extraReducers: {},
});
export const userSelector = (state) => state.settings;
