import { createSlice } from "@reduxjs/toolkit";

export const transactionSlice = createSlice({
  name: "transaction",
  initialState: {
    tableList: [
      {
        key: 1,
        name: "News one",
        description: "Lorem Ipsum",
        change: false,
      },
    ],
    transactionList: [
      {
        key: 0,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 1,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 2,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 3,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 4,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 5,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 6,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 7,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 8,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 9,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
    ],
  },
  reducers: {
    // Reducer comes here
  },
  extraReducers: {
    // Extra reducer comes here
  },
});
export const userSelector = (state) => state.transaction;
