import { createSlice } from "@reduxjs/toolkit";

export const transactionSlice = createSlice({
  name: "transaction",
  initialState: {
    transactionList: [
      {
        key: 0,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 1,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 2,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 3,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 4,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 5,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 6,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 7,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 8,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
      {
        key: 9,
        id: 2,
        email: "name.example@gmail.com",
        phone: null,
        name: null,
        last_name: null,
        verification_code: null,
        password: "123456",
        avatar: null,
        forgot_password_code: null,
        currency: null,
        lang: null,
        last_login: "2021-09-29T15:05:12.611Z",
        tfa_code: null,
        status: false,
        is_affiliate: false,
        created_date: "2021-09-29T15:05:12.613Z",
        updated_date: "2021-09-29T15:05:12.613Z",
        wallets: [],
        walletAddresses: [],
      },
    ],
    savingList: [
      {
        key: 0,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 1,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 2,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 3,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 4,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 5,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 6,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
      {
        key: 7,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "00000000",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        type: "Flexible",
        operation_type: "active",
      },
    ],
    sendList: [
      {
        key: 0,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 1,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 2,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 3,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 4,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 5,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 6,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
      {
        key: 7,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        sum: " 30 ",
        coin: " 20 ",
        tx_id: " 100 ",
        operation_type: " 100 ",
        type: "Internal",
        transaction_status: "active",
      },
    ],
    swapList: [
      {
        key: 0,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 1,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 2,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 3,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 4,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 5,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 6,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
      {
        key: 7,
        date_operation: "01.10.2021",
        email: "email@email.com",
        phone: "s",
        coin_to_coin: " 20 / 30",
        tx_id: " 100 ",
        status_operation: "active",
      },
    ],
  },
  reducers: {
    // Reducer comes here
  },
  extraReducers: {
    // Extra reducer comes here
  },
});
export const userSelector = (state) => state.transaction;
